#!/usr/bin/env bash

## for japanese input
#export GTK_IM_MODULE='uim'
#export QT_IM_MODULE='uim'
#uim-xim &
#export XMODIFIERS='@im=uim'

#uim-toolbar-gtk3-systray &

# right now, this doesn't actually do anything.

#read ~/Xmodmap if it exists
#if [[ -f "${HOME}/.Xmodmap" ]]; then
#	xmodmap "${HOME}/.Xmodmap"
#fi

#if comfortable-swipe program exists

#if [[ -f "${HOME}/comfortable-swipe" ]]; then
#	comfortable-swipe start
#fi
